"use client";

import { useState } from "react";
import { FileText, ChevronDown, ChevronUp } from "lucide-react";

interface NarrativeReportProps {
  narrative: string;
}

function formatNarrative(text: string) {
  return text
    .replace(/\*\*(.*?)\*\*/g, "<strong>$1</strong>")
    .replace(/\*(.*?)\*/g, "<em>$1</em>")
    .replace(/^### (.*$)/gm, "<h3>$1</h3>")
    .replace(/^## (.*$)/gm, "<h2>$1</h2>")
    .replace(/^# (.*$)/gm, "<h1>$1</h1>")
    .replace(/^- (.*$)/gm, "<li>$1</li>")
    .replace(/(<li>.*<\/li>\n?)+/g, "<ul>$&</ul>")
    .replace(/\n\n/g, "</p><p>")
    .replace(/\n/g, "<br/>");
}

export default function NarrativeReport({ narrative }: NarrativeReportProps) {
  const [expanded, setExpanded] = useState(true);

  return (
    <div className="rounded-2xl bg-card/60 backdrop-blur-md border border-border p-7">
      <button
        onClick={() => setExpanded(!expanded)}
        className="w-full flex items-center justify-between mb-4 bg-transparent border-none cursor-pointer p-0"
      >
        <h3 className="text-lg font-bold text-foreground flex items-center gap-2.5">
          <FileText size={20} className="text-chart-5" />
          AI Clinical Narrative Report
        </h3>
        {expanded ? (
          <ChevronUp size={20} className="text-muted-foreground" />
        ) : (
          <ChevronDown size={20} className="text-muted-foreground" />
        )}
      </button>

      {expanded && (
        <div className="animate-fade-in">
          <div className="flex items-center gap-2.5 mb-4 px-3.5 py-2.5 rounded-xl bg-primary/[0.06] border border-primary/10">
            <div className="w-2 h-2 rounded-full bg-primary flex-shrink-0" />
            <p className="text-xs text-primary">
              Generated by Azure OpenAI -- Modeled after Harvard Medical School neurology protocols
            </p>
          </div>

          <div
            className="px-6 py-5 rounded-2xl bg-background/50 border border-border
              [&_h1]:text-2xl [&_h1]:font-bold [&_h1]:mt-6 [&_h1]:mb-3 [&_h1]:text-secondary-foreground
              [&_h2]:text-xl [&_h2]:font-semibold [&_h2]:mt-5 [&_h2]:mb-2 [&_h2]:text-primary [&_h2]:border-b [&_h2]:border-border [&_h2]:pb-2
              [&_h3]:text-lg [&_h3]:font-semibold [&_h3]:mt-4 [&_h3]:mb-1.5 [&_h3]:text-chart-5
              [&_p]:my-2 [&_p]:leading-relaxed [&_p]:text-secondary-foreground [&_p]:text-sm
              [&_ul]:pl-6 [&_ul]:my-2 [&_ul]:list-disc
              [&_li]:my-1 [&_li]:text-secondary-foreground [&_li]:text-sm [&_li]:leading-relaxed
              [&_strong]:text-foreground [&_strong]:font-semibold
              [&_em]:text-chart-5 [&_em]:italic"
            dangerouslySetInnerHTML={{ __html: formatNarrative(narrative) }}
          />
        </div>
      )}
    </div>
  );
}
